### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by remi64000** [tametsi/adnexos#3]
Hello, 

I have a network problem:

![2024-09-12 11_22_26-Window](https://github.com/user-attachments/assets/3189e5f4-01c0-4f20-ab99-0ab62120c131)

The network used by Adnexos is the same than my VPN Wireguard 192.168.16.0/20
So, i can't access to my serveur using my VPN, only local acces is possible.

Is it possible to use the default network 172.x.x.x ?

Have a nice Day!

**Comment by tametsi** [comment]
Hi,

could you please describe in detail what you have done and which parts need to be changed for it to work properly?

Thanks in advance

**Comment by remi64000** [comment]
The problem is that Adnexos creates a network in 192.168.16.0/20 on my server which conflicts with my wireguard VPN.
Suddenly, using my VPN, I can no longer access my server.
I would like Adnexos to create a default network in 172.x.x.x by default, like my other containers.
How can I proceed please?
Good day,
Remi.

**Comment by remi64000** [comment]
OK, i've solved the problem using "/etc/docker/daemon.json" file with:
{"default-address-pools":[{"base":"172.80.0.0/16","size":24},{"base":"172.90.0.0/16","size":24}]}

I don't why my bridge suddenly use a 192.168.16.0/20 pool.

**Comment by tametsi** [comment]
Alright, happy to hear you solved the issue.
